import 'package:the_movie_booking_app/data/vos/date_vo.dart';
import 'package:the_movie_booking_app/data/vos/movie_seat_vo.dart';
import 'package:the_movie_booking_app/utils/constants.dart';

// List<MovieSeatVO> dummyMovieSeats = [
//   MovieSeatVO(title: "A", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "", type: SEAT_TYPE_EMPTY),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_EMPTY),
//   MovieSeatVO(title: "A", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "B", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "B", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "C", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "C", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "D", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "D", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "E", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_TAKEN),
//   MovieSeatVO(title: "", type: SEAT_TYPE_TAKEN),
//   MovieSeatVO(title: "", type: SEAT_TYPE_TAKEN),
//   MovieSeatVO(title: "", type: SEAT_TYPE_TAKEN),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "E", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "F", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "F", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "G", type: SEAT_TYPE_TEXT),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "", type: SEAT_TYPE_AVAILABLE),
//   MovieSeatVO(title: "G", type: SEAT_TYPE_TEXT),
// ];

List<DateVO> dummyDates = [
  DateVO("Sat", "12", "2021-02-12", true),
  DateVO("Sun", "13", "2021-02-13", false),
  DateVO("Mon", "14", "2021-02-14", false),
  DateVO("Tue", "15", "2021-02-15", false),
  DateVO("Wed", "16", "2021-02-16", false),
  DateVO("Thu", "17", "2021-02-17", false),
  DateVO("Fri", "18", "2021-02-18", false),
  DateVO("Sat", "19", "2021-02-19", false),
  DateVO("Sun", "20", "2021-02-20", false),
  DateVO("Mon", "21", "2021-02-21", false),
];
