/// Generic Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;
const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_CARD_REGULAR_2X = 18.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_SMALL_2 = 11.0;
const TEXT_SMALL = 8.0;

/// App Specific
const PRIMARY_BUTTON_HEIGHT = 55.0;
const PRIMARY_BUTTON_BORDER_WIDTH = 0.6;
const PRIMARY_BUTTON_ICON_SIZE = 35.0;
const SIGN_IN_SCREEN_TOP_MARGIN = 100.0;
const MOVIE_LIST_IMAGE_HEIGHT = 190.0;
const MOVIE_LIST_IMAGE_WIDTH = 130.0;
const HORIZONTAL_MOVIE_LIST_HEIGHT = 240.0;
const CIRCULAR_PROFILE_IMAGE_SIZE = 45.0;
const MOVIE_DETAILS_PLAY_BUTTON_SIZE = 60.0;
const MOVIE_DETAILS_CAST_SIZE = 70.0;
const MOVIE_DETAIL_SCREEN_MARGIN_BOTTOM = 100.0;
const WELCOME_SCREEN_IMAGE_SIZE = 250.0;
const MOVIE_DETAILS_PLOT_LINE_HEIGHT = 1.5;
const DRAWER_HEADER_TOP_MARGIN = 120.0;
const MOVIE_TIME_DATE_LIST_HEIGHT = 88.0;
const COMBO_SET_BUTTON_GROUP_SIZE = 35.0;
const CARD_CAROUSEL_HEIGHT = 180.0;
const VISA_LOGO_WIDTH = 50.0;
const VISA_LOGO_HEIGHT = 25.0;
const TICKET_MOVIE_POSTER_HEIGHT = 180.0;
const BARCODE_WIDTH = 250.0;
const BARCODE_HEIGHT = 80.0;
const MOVIE_TICKET_ELEVATION = 16.0;
