/// Hive Types
const int HIVE_TYPE_ID_USER_VO = 1;
const int HIVE_TYPE_ID_CARD_VO = 2;
const int HIVE_TYPE_ID_MOVIE_VO = 3;
const int HIVE_TYPE_ID_GENRE_VO = 4;
const int HIVE_TYPE_ID_CAST_VO = 5;
const int HIVE_TYPE_ID_SNACK_VO = 6;
const int HIVE_TYPE_ID_CINEMA_VO = 7;
const int HIVE_TYPE_ID_TIMESLOT_VO = 8;
const int HIVE_TYPE_ID_CINEMA_LIST_FOR_HIVE_VO = 9;
const int HIVE_TYPE_ID_PAYMENT_VO = 10;

/// Box Names
const String BOX_NAME_USER_VO = "BOX_NAME_USER_VO";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_CAST_VO = "BOX_NAME_CAST_VO";
const String BOX_NAME_SNACK_VO = "BOX_NAME_SNACK_VO";
const String BOX_NAME_CINEMA_VO = "BOX_NAME_CINEMA_VO";
const String BOX_NAME_CINEMA_LIST_FOR_HIVE_VO = "BOX_NAME_CINEMA_LIST_FOR_HIVE_VO";
const String BOX_NAME_PAYMENT_VO = "BOX_NAME_PAYMENT_VO";